// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

#nullable enable annotations

namespace FileOrkestrator.Integrate.SearchEngine.Generated
{
    /// <summary>External Search Engine API</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface ISearchEngineApi
    {
        /// <summary>Поставить задачу индексации источника или набора путей</summary>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/v1/index/jobs")]
        Task<StartIndexJobResponse> StartIndexJob([Body] StartIndexJobRequest body, CancellationToken cancellationToken = default);

        /// <summary>Получить статус задачи индексации</summary>
        [Headers("Accept: application/json")]
        [Get("/api/v1/index/jobs/{jobId}")]
        Task<IndexJobStatus> GetIndexJob(string jobId, CancellationToken cancellationToken = default);

        /// <summary>Запросить отмену задачи индексации</summary>
        [Headers("Accept: application/json")]
        [Delete("/api/v1/index/jobs/{jobId}")]
        Task CancelIndexJob(string jobId, CancellationToken cancellationToken = default);

        /// <summary>Поиск по индексу</summary>
        [Headers("Accept: application/json")]
        [Get("/api/v1/search")]
        Task<SearchResponse> Search([Query] string q, [Query] int? skip, [Query] int? take, CancellationToken cancellationToken = default);


    }

}

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace FileOrkestrator.Integrate.SearchEngine.Generated
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class StartIndexJobRequest
    {

        /// <summary>
        /// Логический источник данных (каталог, share, bucket и т.д.)
        /// </summary>
        [JsonPropertyName("sourceId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid SourceId { get; set; } = default!;

        /// <summary>
        /// Опционально — конкретные пути; если пусто — полная переиндексация источника
        /// </summary>
        [JsonPropertyName("filePaths")]
        public ICollection<string> FilePaths { get; set; } = default!;

        /// <summary>
        /// Ключ идемпотентности для повторных POST с тем же смыслом
        /// </summary>
        [JsonPropertyName("idempotencyKey")]
        public string IdempotencyKey { get; set; } = default!;

        /// <summary>
        /// Идентификатор для сквозной трассировки (логи/метрики)
        /// </summary>
        [JsonPropertyName("correlationId")]
        public string CorrelationId { get; set; } = default!;

        private IDictionary<string, object>? _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class StartIndexJobResponse
    {

        /// <summary>
        /// Идентификатор задачи у Search Engine
        /// </summary>
        [JsonPropertyName("jobId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string JobId { get; set; } = default!;

        [JsonPropertyName("acceptedAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset AcceptedAt { get; set; } = default!;

        /// <summary>
        /// true если запрос с тем же idempotencyKey уже обрабатывался
        /// </summary>
        [JsonPropertyName("isDuplicate")]
        public bool IsDuplicate { get; set; } = default!;

        private IDictionary<string, object>? _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class IndexJobStatus
    {

        [JsonPropertyName("jobId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string JobId { get; set; } = default!;

        [JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonConverter(typeof(JsonStringEnumConverter<IndexJobState>))]
        public IndexJobState Status { get; set; } = default!;

        /// <summary>
        /// Доля выполнения, если известна
        /// </summary>
        [JsonPropertyName("progress")]
        [System.ComponentModel.DataAnnotations.Range(0F, 1F)]
        public float Progress { get; set; } = default!;

        [JsonPropertyName("indexedCount")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int IndexedCount { get; set; } = default!;

        [JsonPropertyName("failedCount")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int FailedCount { get; set; } = default!;

        [JsonPropertyName("errorMessage")]
        public string? ErrorMessage { get; set; } = default!;

        [JsonPropertyName("startedAt")]
        public System.DateTimeOffset? StartedAt { get; set; } = default!;

        [JsonPropertyName("completedAt")]
        public System.DateTimeOffset? CompletedAt { get; set; } = default!;

        /// <summary>
        /// true если завершено с ошибками по части документов
        /// </summary>
        [JsonPropertyName("partialSuccess")]
        public bool PartialSuccess { get; set; } = default!;

        private IDictionary<string, object>? _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum IndexJobState
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Pending")]
        Pending = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Running")]
        Running = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Succeeded")]
        Succeeded = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Failed")]
        Failed = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"Cancelled")]
        Cancelled = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"PartialSuccess")]
        PartialSuccess = 5,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SearchResponse
    {

        [JsonPropertyName("items")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<SearchHit> Items { get; set; } = new System.Collections.ObjectModel.Collection<SearchHit>();

        [JsonPropertyName("totalCount")]
        [System.ComponentModel.DataAnnotations.Range(0L, long.MaxValue)]
        public long TotalCount { get; set; } = default!;

        private IDictionary<string, object>? _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SearchHit
    {

        [JsonPropertyName("documentId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DocumentId { get; set; } = default!;

        [JsonPropertyName("title")]
        public string? Title { get; set; } = default!;

        [JsonPropertyName("snippet")]
        public string? Snippet { get; set; } = default!;

        [JsonPropertyName("score")]
        public double? Score { get; set; } = default!;

        [JsonPropertyName("sourcePath")]
        public string? SourcePath { get; set; } = default!;

        private IDictionary<string, object>? _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ErrorResponse
    {

        [JsonPropertyName("code")]
        public string Code { get; set; } = default!;

        [JsonPropertyName("message")]
        public string Message { get; set; } = default!;

        [JsonPropertyName("detail")]
        public string? Detail { get; set; } = default!;

        private IDictionary<string, object>? _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765